from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., description="The user query input to the AI assistant")


class ChatResponse(BaseModel):
    reply: str = Field(..., description="The answer generated by the assistant")
    source: str = Field(..., description="The routing source of the reply: 'gemini' or 'simulation'")
    timestamp: str = Field(..., description="ISO 8601 formatted timestamp of the reply generation")
    confidence: float = Field(..., description="Confidence score of the match, from 0.0 to 1.0")
